### PR TITLE
made compatible with mysql 8

### PR DESCRIPTION
**Pull request by t-schroeder**
GROUPING has become a reserved keyword in MySQL 8.0.1. The column "grouping" from checkbox_item has therefore been renamed to "groupingid".

### CODE REVIEW

**Comment by davosmith** [comment]
Change looks good to me - merged

**Comment by davosmith** [comment]
@t-schroeder looks like you missed a few renames - thankfully behat tests caught them, so I've been through the code and fixed the last few of them.

**Comment by t-schroeder** [comment]
Sorry for missing these. Thought i got all.

**Comment by davosmith** [comment]
Not a problem - thanks for the fix in the first place :-)

**Pull request merged**
